### ISSUE TITLE
ModuleNotFoundError: No module named 'hpolib'

### ISSUE THREAD

**Issue by cysun0226** [jkirschner42/LineBO#4]
Hi, 

I got an error when executing the command `febo create {experiment_name} --config config/{experiment_name}.yaml` :
```
  File "/linebo/LineBO/febo/environment/benchmarks/hpolib.py", line 2, in <module>
    import hpolib.benchmarks.synthetic_functions as hpobench
ModuleNotFoundError: No module named 'hpolib'
```

It seems that `git+https://github.com/automl/HPOlib2` will be redirected to [https://github.com/automl/HPOBench](https://github.com/automl/HPOBench) .
The old version of the benchmarking library now is moved to [https://github.com/automl/HPOlib1.5](https://github.com/automl/HPOlib1.5).

I change the pip command in the readme to:
```
pip install git+https://github.com/automl/HPOlib1.5
```
and the issue is solved.

Thank you for the work & sharing your code!

**Comment by kirschnj** [comment]
Updated. Thank you!
